=== DianaM411/LibreriaXML/reglas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

<xs:element name="libreria">
  <xs:complexType>
    <xs:sequence>
     <!-- LIBRO: minimo 4 libros, maximo 100 -->
          <xs:element name="libro" minOccurs="4" maxOccurs="100">
            <xs:complexType>
              <xs:sequence>
            
                <xs:element name="codigo">
                  <xs:simpleType>
                  <xs:restriction base="xs:string">
                  <xs:pattern value="[A-Z]{3}[0-9]{4}[(!*?=.@#$%^+)]{2}"/>
                  </xs:restriction>
                  </xs:simpleType>
                </xs:element>

                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="autor" type="xs:string"/>
                <!-- FECHA es opcional -->
                <xs:element name="fecha" type="xs:date" minOccurs="0" maxOccurs="1"/>
                <!-- PRECIO por defecto es 9.99, pero se puede cambiar -->
                <xs:element name="precio" type="xs:decimal" default="9.99"/>
              </xs:sequence>
              <xs:attribute name="categoria" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <!-- CATEGORIA: hay que elegir una de las 4  -->
                <xs:pattern value="Misterio|Romantico|Paranormal|SelfHelp"/>
                </xs:restriction>
              </xs:simpleType>
          </xs:attribute>
            </xs:complexType>
          </xs:element>

    
          <!-- CLIENTE: minimo 1 y maximo 2 -->
          <xs:element name="cliente" minOccurs="1" maxOccurs="2">
              <xs:complexType>
              <xs:sequence>
                
                <xs:element name="codigoCliente">
                  <xs:simpleType>
                  <xs:restriction base="xs:string">
                  <xs:pattern value="[A-Z]{3}[0-9]{4}[(?=.@#$%^+)]"/>
                  </xs:restriction>
                  </xs:simpleType>
                  </xs:element>

                <xs:element name="nombre" type="xs:string"/>
                <!-- APELLIDOS: maximo 4 -->
                <xs:element name="apellido" type="xs:string" maxOccurs="4"/>
                <!-- DIRECCION: es opcional -->
                <xs:element name="direccion" type="xs:string" minOccurs="0"/>
                <xs:element name="telefono" type="xs:string"/>
                <xs:element name="correo" type="xs:string"/>
                <xs:element name="fechaNacimiento" type="xs:date"/>
                <xs:element name="subscritoNewsletter">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <!-- SUBSCRITO: puedes elegir si o no -->
                      <xs:pattern value="si|no"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>

              </xs:sequence>
              <xs:attribute name="nivel">
            <xs:simpleType>
              <!-- NIVEL: puedes elegir entre 3 opciones -->
            <xs:restriction base="xs:string">
            <xs:enumeration value="Basic"/>
            <xs:enumeration value="Medio"/>
            <xs:enumeration value="VIP"/>
            </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
              </xs:complexType>
          </xs:element>

</xs:sequence>   
</xs:complexType>
</xs:element>
</xs:schema>

=== DianaM411/LibreriaXML/libreria2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo.xsl"?>
<libreria xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com reglas.xsd">

  <libro categoria="Misterio">
  <!-- CODIGO: 3 letras mayuscula, 4 numeros, 2 caracteres especiales -->
    <codigo>REC1234*!</codigo>
    <titulo>The best book ever</titulo>
    <autor>Diana Munteanu</autor>
  <!-- la fecha es opcional -->
    <precio>9.90</precio>
  </libro>

  <libro categoria="SelfHelp">
    <codigo>REC1234*#</codigo>
    <titulo>My story</titulo>
    <autor>Diana Munteanu</autor> 
    <precio>9.90</precio>
  </libro>

  <libro categoria="Paranormal">
    <codigo>REC1234*#</codigo>
    <titulo>True Blood</titulo>
    <autor>Charlaine Harris</autor>  
    <precio>9.90</precio>
  </libro>

  <libro categoria="Romantico">
    <codigo>REC1234*#</codigo>
    <titulo>Our love story</titulo>
    <autor>Nora Roberts</autor>
    <precio>9.90</precio>
  </libro>


  <cliente nivel="VIP">
    <!-- CODIGO: 3 letras mayuscula, 4 numeros, 1 caracter especial  -->
    <codigoCliente>AAA1234$</codigoCliente>
    <nombre>Diana</nombre>
    <apellido>Munteanu</apellido>
    <!-- La direccion es opcional. En el otro XML no hay direccion  -->
    <direccion>Calle calle numero 4</direccion>
    <telefono>123456789</telefono>
    <correo>dianamunteanu333@gmail.com</correo>
    <fechaNacimiento>1994-11-04</fechaNacimiento>
    <subscritoNewsletter>si</subscritoNewsletter>
  </cliente>

  <cliente nivel="Basic">
    <codigoCliente>ABC1234$</codigoCliente>
    <nombre>Estela</nombre>
    <!-- En este XML tenemos un cliente con 4 apellidos  -->
    <apellido>Gomez</apellido>
    <apellido>Moreno</apellido>
    <apellido>JungKook</apellido>
    <apellido>Beyonce</apellido>
    <direccion>Calle calle numero 4</direccion>
    <telefono>122345678</telefono>
    <correo>estelag@gmail.com</correo>
    <fechaNacimiento>1996-06-19</fechaNacimiento>
    <subscritoNewsletter>no</subscritoNewsletter>
  </cliente>

</libreria>
